name: 기능 추가 요청
description: 새로운 기능이나 시스템 추가를 위한 이슈 템플릿입니다.
title: "[Feature] 기능 이름 요약"
labels: ["feature", "pending"]

body:
  - type: input
    id: summary
    attributes:
      label: 📝 기능 요약
      description: 구현할 기능을 간단하게 설명해주세요.
      placeholder: ex) 플레이어 점프 기능 추가

  - type: textarea
    id: detail
    attributes:
      label: 📌 상세 설명
      description: 기능의 동작 방식, 주요 흐름, 기대 효과 등을 자세히 작성해주세요.
      placeholder: |
        - 스페이스바 입력 시 캐릭터 점프
        - 장애물 회피를 위한 기능

  - type: textarea
    id: classplan
    attributes:
      label: 🧩 예상 클래스 및 메서드
      description: 예상되는 클래스 이름, 책임, 주요 메서드를 간단히 정리해주세요.
      placeholder: |
        - JumpController: 입력 감지 및 점프 처리
        - PhysicsHandler: 중력 적용

        - type: textarea
          id: note
          attributes:
            label: 📝 참고 사항
            description: 관련 문서, 디자인 참고 자료, 또는 이슈 간 링크가 있다면 적어주세요.
            placeholder: ex) #42 이동 시스템과 연계 필요

        - type: checkboxes
          id: checklist
          attributes:
            label: ✅ 체크리스트
            description: 아래 항목을 확인해주세요.
            options:
              - label: 해당 기능은 중복되지 않습니다.
                required: true
              - label: 다른 팀원과 협업 범위를 확인했습니다.
              - label: 명세서 작성을 염두에 두고 설계 중입니다.
